# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/borgearthur/CLionProjects/BrickOut

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/borgearthur/CLionProjects/BrickOut/cmake-build-debug-wsl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Samsung/CLionProjects/BrickOut/cmake-build-debug-wsl/CMakeFiles /mnt/c/Users/borgearthur/CLionProjects/BrickOut/cmake-build-debug-wsl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Samsung/CLionProjects/BrickOut/cmake-build-debug-wsl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BrickOut

# Build rule for target.
BrickOut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BrickOut
.PHONY : BrickOut

# fast build rule for target.
BrickOut/fast:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/build
.PHONY : BrickOut/fast

src/keyboard.o: src/keyboard.c.o

.PHONY : src/keyboard.o

# target to build an object file
src/keyboard.c.o:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/keyboard.c.o
.PHONY : src/keyboard.c.o

src/keyboard.i: src/keyboard.c.i

.PHONY : src/keyboard.i

# target to preprocess a source file
src/keyboard.c.i:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/keyboard.c.i
.PHONY : src/keyboard.c.i

src/keyboard.s: src/keyboard.c.s

.PHONY : src/keyboard.s

# target to generate assembly for a file
src/keyboard.c.s:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/keyboard.c.s
.PHONY : src/keyboard.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/main.c.s
.PHONY : src/main.c.s

src/screen.o: src/screen.c.o

.PHONY : src/screen.o

# target to build an object file
src/screen.c.o:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/screen.c.o
.PHONY : src/screen.c.o

src/screen.i: src/screen.c.i

.PHONY : src/screen.i

# target to preprocess a source file
src/screen.c.i:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/screen.c.i
.PHONY : src/screen.c.i

src/screen.s: src/screen.c.s

.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.c.s:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/screen.c.s
.PHONY : src/screen.c.s

src/timer.o: src/timer.c.o

.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) -f CMakeFiles/BrickOut.dir/build.make CMakeFiles/BrickOut.dir/src/timer.c.s
.PHONY : src/timer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BrickOut"
	@echo "... src/keyboard.o"
	@echo "... src/keyboard.i"
	@echo "... src/keyboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/screen.o"
	@echo "... src/screen.i"
	@echo "... src/screen.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system